urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
   url(r'^import/', views.import_data, name="import"),
]

models.py
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone


@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text
    answer = models.IntegerField()


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)


    def __str__(self):
        return self.choice_text

views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseBadRequest , HttpResponse
import pyexcel.ext.xlsx
from models import Question , Choice

from django.template import RequestContext
from django import forms

class UploadFileForm(forms.Form):
 file = forms.FileField(label='')

def import_data(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)
        if form.is_valid():
            file_name = request.FILES['file']
            sheet = file_name.get_sheet()
            records = sheet.to_records()
            for record in records:
                keys = record.keys()
                key_1 = keys[1]
                quest_text = record[key_1]
                key_2 = keys[2]
                choice1 = record[key_2]; key_3 = keys[3]
                choice2 = record[key_3]
                key_4 = keys[4]
                choice3 = record[key_4]
                key_0 = keys[0]
                choice4 = record[key_0]
                key_5 = keys[5]
                answer= record[key_5]
                q=Question(quest_text,answer)
                q.save()
                id_quest = q.id
                c1 = Choice(id_quest,choice1)
                c1.save()
                c2 = Choice(id_quest,choice2)
                c2.save()
                c3 = Choice(id_quest,choice3)
                c3.save()
                c4 = Choice(id_quest,choice4)
                c4.save()
            return HttpResponse("OK", status=200)
        else:
            return HttpResponseBadRequest()


    else:
        form = UploadFileForm()

    return render_to_response(
        'upload_form.html',
        {
                'form': form,
                'title': 'Import excel data into database example',
                'header': 'Please upload sample-data.xls:'
        },
            context_instance=RequestContext(request))

templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

templates/polls/import.html
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1>{{header}}</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" enctype="multipart/form-data"  method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}

    <ul>
    {% for question in latest_question_list %}
       <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/polls/upload_form.html
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1>{{header}}</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" enctype="multipart/form-data"  method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>